# Generated by Django 5.0.1 on 2024-03-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_name',
        ),
    ]
