# Generated by Django 5.0.1 on 2024-03-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_remove_movie_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='reviewer_name',
            new_name='movie_name',
        ),
    ]
